import styles from './Layout.module.css';
import Head from 'next/head';

export default function Layout({ children }) {
    return (
        <>
        <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        </Head>
        <div className={styles.container}>
            <header className={styles.header}>
                <h1>Blog App</h1>
            </header>
            <div className={styles.main}>{children}</div>
        </div>
        </>
    );
}
